chore: update controller-gen to v0.9.1
rhobs/observability-operator pull request #173
Opened 2022-07-06 13:50 UTC by jan--f

This mostly pulls in many fixes from controller-tools. Mainly
controller-gen now respects type marker in types and generated the CRD
manifests accordingly. This means that SSA now functions correctly with
the generated manifests. Accordingly this also reenables the
`revert-test`.
The other changes added here are mostly whitespace changes in the
manifests, the status being no longer included in the CRD manifests (see
https://github.com/kubernetes-sigs/controller-tools/issues/456 for
details) and we seem to have forgotten to regenerate some manifests
after a version bump.

Fixes: https://github.com/rhobs/observability-operator/issues/142

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

2022-07-06 14:04 UTC, simonpasquier approved these changes

2022-07-07 05:10 UTC, sthaha commented
lgtm except for the broken CI 🤔

2022-07-08 12:52 UTC, jan--f commented
Ok the CRD manifest errors where due to a bug in controller-gen. v0.9.2 ships a fix for this.

2022-07-08 13:22 UTC, simonpasquier submitted a review, later dismissed

2022-07-10 23:38 UTC, sthaha commented on hack/kind/setup.sh
> +fi
Unrelated change :( 

Also ... IMHO, we shouldn't install tools / make changes to users system other than in locations known/announced to them. E.g. `make tools` is explicit and installs to `<prj>/tmp/bin`

2022-07-10 23:41 UTC, sthaha requested changes
Requesting changes only due to an unrelated change (`hack/setup.sh`). 
Merging this would squash the commits (only policy enabled for this repo)

2022-07-11 17:50 UTC, jan--f commented
> Requesting changes only due to an unrelated change (`hack/setup.sh`). Merging this would squash the commits (only policy enabled for this repo)

Thanks good catch. I had that change in for testing. I'm actually proposing it in #175. Dropped it now.

2022-07-12 06:10 UTC, sthaha approved these changes

2022-07-12 06:11 UTC, merged