fix:do not report Available=degraded condition
rhobs/observability-operator pull request #189
Opened 2022-09-07 08:27 UTC by tremes

The convention is to report only true,false or unknown as the condition status value.

2022-09-07 15:15 UTC, simonpasquier reviewed
I wonder if we shouldn't have different Reasons depending on the Prometheus status. E.g.
* Prometheus(Condition=Available,Status=Degraded) -> MonitoringStack(Condition=Available,Status=False,Reason=PrometheusDegraded)
* Prometheus(Condition=Available,Status=False) -> MonitoringStack(Condition=Available,Status=False,Reason=PrometheusNotAvailable)

2022-09-08 01:09 UTC, sthaha requested changes
Could the commit message please include link to the Jira and a bit of reasoning behind this change? 
 
E.g.

```
fix: report Available=false when prometheus is degraded

This PR changes the status.condition to adhere to the convention to
report a condition as  true, false, or unknown. 

jira: link

signed-by: 
```

2022-09-08 07:59 UTC, simonpasquier approved these changes
lgtm

2022-09-09 00:20 UTC, sthaha approved these changes
/lgtm 

Thanks you @tremes for the patch 🙇

2022-09-09 00:20 UTC, merged