feat: expose prometheus nodeselector and tolerations in monitoringstack CRD
rhobs/observability-operator pull request #293
Opened 2023-05-25 09:33 UTC by bng0y

Allows to isolate the Prometheus pods when necessary. 
Context: https://issues.redhat.com/browse/SDE-2823

2023-05-25 12:53 UTC, simonpasquier reviewed
Maybe the fields should be located under `.spec` rather than `.spec.prometheusConfig` and apply to all child resources of the MonitoringStack resource?

@sthaha @jan--f WDYT?

2023-05-25 23:01 UTC, sthaha commented
> Maybe the fields should be located under `.spec` rather than `.spec.prometheusConfig` and apply to all child resources of the MonitoringStack resource?

@simonpasquier, I like the idea to have a global setting for all child resources, however should we also allow each child resource to have different setting to the global one?

2023-05-25 23:03 UTC, sthaha commented
> If this PR changes the Prometheus `managedFields`, please update [this test case](https://github.com/rhobs/observability-operator/blob/main/test/e2e/monitoring_stack_controller_test.go#L601C1-L656) to keep managed Fields info updated.

@vimalk78 shouldn't that test fail in that case 🤔

2023-05-26 01:42 UTC, vimalk78 commented
> @vimalk78 shouldn't that test fail in that case 
it would, but the new parameters are optional, so unless explicitly set in the object the managedFields wont change.

2023-05-26 13:57 UTC, simonpasquier commented
@sthaha my gut feeling is that in most cases, you want the monitoring pods to run on the same set of nodes (e.g. infra) so having a top-level field is probably what makes the most sense. We can argue later if there's a need for individual settings for each component but I'd rather make the mainstream situation easy to configure.

2023-05-29 04:12 UTC, sthaha commented
@simonpasquier  +1 to having it global for now 

> We can argue later if there's a need for individual settings for each component but I'd rather make the mainstream situation easy to configure.

+1 to YAGNI :)

2023-05-30 21:52 UTC, sthaha commented on pkg/controllers/monitoring/monitoring-stack/components.go
> +				Tolerations:               config.Tolerations,
@bng0y , Like @simonpasquier suggested, lets make this global and apply the same to all resources that ObO creates.

2023-05-30 21:53 UTC, sthaha requested changes
Could you please consider implementing the suggestion.

2023-06-19 22:59 UTC, sthaha commented
@bng0y , It would be great to have this feature added to ObO. Do you need help implementing this?

2024-07-09 13:40 UTC, closed without merging