test: prometheus scale down e2e test
rhobs/observability-operator pull request #448
Opened 2024-03-28 05:47 UTC by lihongyan1

This should fix test failure [COO-79](https://issues.redhat.com/browse/COO-79)
`monitoring_stack_controller_test.go:585: assertion failed: 0 (prom.Status.Replicas int32) != 1 (int32)`

2024-04-08 07:50 UTC, lihongyan1 commented
@simonpasquier @jan--f Please help review when convenient

2024-04-12 07:28 UTC, jan--f requested changes

2024-04-12 07:28 UTC, jan--f commented on test/e2e/monitoring_stack_controller_test.go
> +	f.AssertPrometheusReplicaStatus(ms.Name, ms.Namespace, numOfRep)
```suggestion
	f.AssertPrometheusReplicaStatus(ms.Name, ms.Namespace, 0)
```
Should this test for scale down to 0?

2024-04-12 07:28 UTC, jan--f commented on test/e2e/framework/assertions.go
> +			t.Fatal(fmt.Errorf("Prometheus %s/%s was not scaled down to %d", namespace, name, expectedReplicas))
```suggestion
			t.Fatal(fmt.Errorf("Prometheus %s/%s has unexpected number of replicas, got %d, expected %d", namespace, name, prom.Status.Replicas, expectedReplicas))
```

2024-04-12 09:20 UTC, lihongyan1 commented on test/e2e/monitoring_stack_controller_test.go
> +	f.AssertPrometheusReplicaStatus(ms.Name, ms.Namespace, numOfRep)
Sorry typo, thanks your sharp eyes

2024-04-15 05:06 UTC, lihongyan1 commented
The fix of PR https://github.com/rhobs/observability-operator/pull/454 can work, case Alertmanager_runs_in_HA_mode failed in https://github.com/rhobs/observability-operator/actions/runs/8660157870/job/23747502573?pr=448, will provide new update to the case Alertmanager_runs_in_HA_mode

2024-04-18 03:28 UTC, lihongyan1 commented
/retest

2024-04-22 14:02 UTC, jan--f approved these changes
/lgtm

2024-04-23 02:12 UTC, lihongyan1 commented
/retest

2024-04-23 03:11 UTC, merged